In [2]:
import tensorflow as tf
import numpy as np
import pandas as pd
import keras
from sklearn.model_selection import train_test_split

In [3]:
from keras.datasets import mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()

In [4]:
x_train, x_test, y_train, y_test = train_test_split(x_train, y_train, test_size=0.33, random_state=42)

In [12]:
a=tf.contrib.layers.flatten(x_train)

In [13]:
y_train

array([8, 6, 9, ..., 0, 0, 4], dtype=uint8)

In [14]:
sess=tf.InteractiveSession()
a=a.eval()

C:\Users\glaedur\Anaconda3\lib\site-packages\tensorflow\python\client\session.py:1711: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '


In [15]:
a=a[:1000,:]
a

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [193]:
w1=np.random.randn(784,100)
w2=np.random.randn(100,10)
w3=np.random.randn(10,1)

In [18]:
y_train[0:5]

array([5, 0, 4, 1, 9], dtype=uint8)

In [48]:
l1=a.dot(w1)

In [49]:
a1=1/(1+np.exp(-l1))

In [50]:
a1.shape

(1000, 100)

In [51]:
l2=a1.dot(w2)

In [52]:
a2=np.maximum(l2,0)

In [53]:
l3=a2.dot(w3)

In [18]:
y_train=y_train[:1000].reshape(1000,1)

In [19]:
y=1.0/(1+np.exp(-y_train))

C:\Users\glaedur\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: overflow encountered in exp
  """Entry point for launching an IPython kernel.


In [83]:
loss = -(y*np.log(a3) + (1-y)*np.log(1-a3))

In [139]:
loss.sum()

nan

In [111]:
d_a3 = (y-a3)/(a3*(1-a3))

In [112]:
d_a3.shape

(1000, 1)

In [86]:
a3.shape

(1000, 1)

In [87]:
d_l3=d_a3*(a3*(1-a3))

In [88]:
d_l3.shape

(1000, 1)

In [89]:
w3.shape

(10, 1)

In [90]:
a2.shape

(1000, 10)

In [91]:
d_w3=a2.T.dot(d_l3)

In [92]:
d_w3.shape

(10, 1)

In [93]:
d_a2=d_l3.dot(w3.T)

In [94]:
d_a2.shape

(1000, 10)

In [21]:
def grad(x):
    if x<0:
        return 0
    else:
        return 1

In [23]:
grad=np.vectorize(grad)

In [97]:
d_l2=grad(a2)

In [98]:
d_l2.shape

(1000, 10)

In [99]:
l2.shape

(1000, 10)

In [100]:
d_w2=a1.T.dot(d_l2)
d_a1=d_l2.dot(w2.T)

In [101]:
d_w2.shape

(100, 10)

In [102]:
w2.shape

(100, 10)

In [103]:
d_a1.shape

(1000, 100)

In [104]:
a1.shape

(1000, 100)

In [105]:
d_l1=d_a1*(a1*(1-a1))

In [106]:
d_l1.shape

(1000, 100)

In [107]:
l1.shape

(1000, 100)

In [108]:
d_w1=a.T.dot(d_l1)

In [109]:
d_w1.shape

(784, 100)

In [110]:
w1.shape

(784, 100)

In [16]:
w1=np.random.randn(784,100)
w2=np.random.randn(100,10)
w3=np.random.randn(10,1)
alpha=0.009

In [24]:
for t in range(10):
    l1=a.dot(w1)
    a1=1.0/(1+np.exp(-l1))
    l2=a1.dot(w2)
    a2=np.maximum(l2,0)
    l3=a2.dot(w3)
    a3=1.0/(1+np.exp(-l3))
    loss = -(y*np.log(a3) + (1-y)*np.log(1-a3))
    d_a3 = (y-a3)/(a3*(1-a3))
    d_l3=d_a3*(a3*(1-a3))
    d_w3=a2.T.dot(d_l3)
    d_a2=d_l3.dot(w3.T)
    d_l2=grad(a2)
    d_w2=a1.T.dot(d_l2)
    d_a1=d_l2.dot(w2.T)
    d_l1=d_a1*(a1*(1-a1))
    d_w1=a.T.dot(d_l1)
    w1=w1-alpha*d_w1
    w2=w2-alpha*d_w2
    w3=w3-alpha*d_w3
    print("loss is",(loss.sum())/1000)

loss is 1.0886788894836308
loss is 0.6931471805599454
loss is 0.6931471805599454
loss is 0.6931471805599454
loss is 0.6931471805599454
loss is 0.6931471805599454
loss is 0.6931471805599454
loss is 0.6931471805599454
loss is 0.6931471805599454
loss is 0.6931471805599454


In [25]:
a3[:5]

array([[0.5],
       [0.5],
       [0.5],
       [0.5],
       [0.5]])

In [26]:
y[:5]

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.]], dtype=float16)